mysqlpro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from mysqlapp import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.model_form_upload,name="home"),
    path('list/',views.Teacher,name="list")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysqlapp/models.py
from django.db import models
from django.core.validators import RegexValidator

class Teacher(models.Model):
    name=models.CharField(max_length=50)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+91XXXXXXX'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    email=models.EmailField()
    image=models.ImageField()
    date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()

    def __str__(self):
        return self.name

class Student(models.Model):
    name=models.CharField(max_length=25)
    age=models.IntegerField()
    addres=models.TextField()

    def __str__(self):
        return self.name

mysqlapp/forms.py
from django import forms
from mysqlapp.models import Teacher

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"

mysqlapp/views.py
from django.shortcuts import render
from mysqlapp.forms import DocumentForm
from mysqlapp.models import Teacher
from django.views.generic import ListView

def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = DocumentForm()
    return render(request, 'model_form_upload.html', {
        'form': form
    })

class Listview(ListView):
    model = Teacher
    template_name = "list.html"

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for object in teacher_list %}
    {{ object.name }}
    {{ object.email }}
    {{ object.date }}
    {{ object.phone_number }}
    {{ object.address }}
{% endfor %}

</body>
</html>

templates/model_form_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
</body>
</html>